---
title: "pivot_lobsters"
author: "DTC"
date: "17/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')

```

```{r import}

lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip = 4)

## explore data

skimr::skim(lobsters)

```

```{r grouping and summarizing}

## one grouping variable

lobsters %>%
  group_by(year) %>%
  summarize(count_by_year = n()
            )

## two grouping variables

lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_year = n()
            )

## summarize multiple variables
## save summary as object

siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_year = n(),
            mean_size_mm = mean(size_mm, na.rm=TRUE),
            sid_size_mm = sd(size_mm, na.rm=TRUE)
            )

## use kable for formatting

siteyear_summary %>%
  kable()

```

There are `r nrow(lobsters)` total lobsters included in this report. 

```{r activity}

## calculate median lobster size

siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_year = n(),
            mean_size_mm = mean(size_mm, na.rm=TRUE),
            sd_size_mm = sd(size_mm, na.rm=TRUE),
            median_size_mm = median(size_mm, na.rm=TRUE)
            )

ggplot(data = siteyear_summary, aes(
  x = year, y = median_size_mm, colour = site)
  ) +
  geom_line()

ggsave(here("figures", "lobster-site-sizes.jpg"), dpi = 180, width = 8, height = 7)

ggplot(siteyear_summary, aes(x = year, y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)

ggsave(here("figures", "lobster-size-sizes-cols.jpg"), dpi = 180, width = 8, height = 7)
```

```{r summarize_count}

lobsters %>%
  count(site, year)

## This is the same as:
lobsters %>%
  group_by(site, year) %>%
  summarize(n = n()) %>%
  ungroup()

```

There are `r count(lobsters)` total lobsters included in this summary.

```{r mutate_and_select}

lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm / 1000,
         millenia = 2000,
         observer = "Allison Horst")

lobsters_detailed %>%
  select(date, site, size_m)

```

