---
title: "Creating graphs in R with 'ggplot2'"
author: "DTC"
date: "15/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(readxl)
library(here)
```

```{r import csv}
ca_np <- read_csv(here("data", "ca_np.csv"))
```

```{r examine ca_np file}
names(ca_np)
head(ca_np)
summary(ca_np)
```

```{r import xlsx file}

ci_np <- read_excel(here("data", "ci_np.xlsx"))

```

```{r examine ci_np file}

view(ci_np)
names(ci_np)
head(ci_np)
summary(ci_np)
```

```{r plotting}

gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))

gg_base +
  geom_point(
    colour = "purple",
    pch = 18,
    size = 4
  ) +
  geom_point(
    colour = "white",
    pch = 18,
    size = 2
  )

gg_base +
  geom_point(
    aes(size = visitors,
        colour = visitors),
    pch = 18
  )

## Activity
## map variables onto graph aesthetics

gg_base +
geom_col(aes(fill = visitors)
         )


```


# Plots with ggplot2

We are going to make plots in R and it's going to be amazing.
